name: HTML CI/CD Pipeline...

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify HTML File
      run: ls -al && cat index.html

    - name: Simulate deployment
      run: echo "Simulated deployment of static site"
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEMO_GITHUB_TOKEN }}
        publish_dir: .                            
        publish_branch: gh-pages  

