name: HTML CI/CD Pipeline...

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify HTML File
      run: ls -al && cat index.html

    - name: Simulate deployment
      run: echo "Simulated deployment of static site"
